# Generated by Django 4.2.24 on 2025-09-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_contact_name_alter_order_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
