# Generated by Django 4.2.24 on 2025-09-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
